[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 13.0

[font.bold]
family = "JetBrains Mono"
style = "Regular"

[window]
#decorations = "Transparent"
decorations = "buttonless"
opacity = 0.82
blur = true
startup_mode = "Maximized"

[window.padding]
x = 15
y = 16
 
