[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#565656"
blue = "#49a4f8"
cyan = "#99faf2"
green = "#c0e17d"
magenta = "#a47de9"
red = "#ec5357"
white = "#ffffff"
yellow = "#f9da6a"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#000000"
blue = "#47a0f3"
cyan = "#97c9d1"
green = "#6ed48e"
magenta = "#7b5cb0"
red = "#eb5c52"
white = "#e5e9f0"
yellow = "#f6c744"

[colors.primary]
background = "#000000"
foreground = "#f2f2f2"

[font]
size = 12.0

[font.bold]
family = "Menlo"
style = "Regular"

[font.bold_italic]
family = "Menlo"
style = "Bold Italic"

[font.italic]
family = "Menlo"
style = "Italic"

[font.normal]
style = "Regular"

[font.offset]
x = 0
y = 2

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "buttonless"
opacity = 0.85
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0
