[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12.0
 
[font.bold]
family = "Menlo"
style = "Regular"

[window]
decorations = "buttonless"
opacity = 0.82
blur = true
startup_mode = "Maximized"
 
[window.padding]
x = 5
y = 5
 
